
export const FETCH_BATCHES = 'FETCH_BATCHES'
export const FETCH_ONE_BATCH = 'FETCH_ONE_BATCH'
export const CREATE_BATCH = 'CREATE_BATCH'
export const REMOVE_BATCH = 'REMOVE_BATCH'

export const FETCH_STUDENTS = 'FETCH_STUDENTS'
export const FETCH_ONE_STUDENT = 'FETCH_ONE_STUDENT'
export const CREATE_STUDENT = 'CREATE_STUDENT'

export const FETCH_EVALUATIONS = 'FETCH_EVALUATIONS'
export const FETCH_ONE_EVALUATION = 'FETCH_ONE_EVALUATION'
export const CREATE_EVALUATION = 'CREATE_EVALUATION'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'